services:
  catalog:
    image: artellas/rust-catalog:1
    container_name: catalog-container
    environment:
      APP_ENVIRONMENT: development
      APP_HTTP_URL: 0.0.0.0:8080
    ports:
      - "8080:8080"
    depends_on:
      catalog-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://0.0.0.0:8080/api/health/ready | grep '\"status\":\"Ok\"' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - rust-microservices-network

  catalog-db:
    image: postgres:18-alpine
    container_name: catalog-db-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - rust-microservices-network
    volumes:
      - catalog-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "PGPASSWORD=postgres pg_isready -U postgres -h catalog-db" ]
      interval: 10s
      timeout: 30s
      retries: 15

volumes:
  catalog-db:

networks:
  rust-microservices-network:
    driver: bridge